### ISSUE TITLE
Glog extraction

### ISSUE THREAD

**Issue by goldbattle** [ethz-asl/glog_catkin#11]
In the latest version, the downloaded zip (v0.3.4.zip) in my case does not extract into the `/glog_src/` folder during build. Currently using the catkin build system. When extracted and placed in the folder the system compiled file once I installed a gcc compiler using `sudo apt-get install build-essential`.

Original Error:
```
[glog_catkin] ==> '/catkin_ws/build/glog_catkin/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j' in '/catkin_ws/build/glog_catkin'
[ 11%] Performing configure step for 'glog_src'
/bin/sh: 1: ./configure: not found
make[2]: *** [glog_src-prefix/src/glog_src-stamp/glog_src-configure] Error 127
make[1]: *** [CMakeFiles/glog_src.dir/all] Error 2
make: *** [all] Error 2
[glog_catkin] <== '/catkin_ws/build/glog_catkin/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j' failed with return code '2'
```

**Comment by simonlynen** [comment]
@goldbattle can you let me know if #12 works for you?

**Comment by goldbattle** [comment]
Yep works great!
Thank you

**Comment by simonlynen** [comment]
@goldbattle thanks for the fast feedback.

**Comment by CarSanoja** [comment]
![screenshot_2](https://user-images.githubusercontent.com/34045195/44630424-32b49100-a912-11e8-9234-06e031b6c55c.png)
Hello, i am getting this error while doing "catkin build"
