### ISSUE TITLE
Error when using catkin build command

### ISSUE THREAD

**Issue by ricardo-zurfluh** [ethz-asl/glog_catkin#15]
After trying to build the packages in the created catkin workspace, I got the following error:

```
Errors     << gflags_catkin:cmake ~/test_catkin_ws/logs/gflags_catkin/build.cmake.002.log                                                                                                                      
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:291 (message):
  catkin_package() absolute include dir
  '~/test_catkin_ws/devel/.private/gflags_catkin/include' does
  not exist
```
 
I used the command "catkin build". Hope getting support. Thank you very much.

**Comment by schneith** [comment]
Could you update the gflags_catkin package to the most recent master, clean the build/devel folder and retry the build?

@tcies might this be related to https://github.com/ethz-asl/gflags_catkin/pull/10?

**Comment by tcies** [comment]
Nope, this is the catkin-tools 0.4.2 that two of our students have also already ran into.
Currently, you have the problem that you [build linked](http://catkin-tools.readthedocs.io/en/latest/advanced/linked_develspace.html?highlight=isolate) (manifested by the `devel/.private` directory).
You can amend that by running `catkin config --isolate_devel` but we ran into some problems with catkin tools 0.4.2 even then (we haven't investigated them further, I suspect there's an issue with package format 2).

We currently have a temporary fix where we downgrade to 0.3.1:
```
sudo apt-get remove python-catkin-tools
sudo apt-get install python-pip
sudo pip install catkin-tools==0.3.1
```

Let's stay in touch about this issue.

**Comment by hitimo** [comment]
@ricardo-zurfluh Did this solve your issue?

**Comment by ricardo-zurfluh** [comment]
@hitimo It's still building, but it seems working. I will confirm if it has worked or not, asap.

**Comment by ricardo-zurfluh** [comment]
The build is complete and returned no errors. So, also the simulation package works well now. Thank you very much for the support.
