### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by XiaoGene** [ethz-asl/glog_catkin#18]
I was building glog_catkin on a Ubuntu 14.04 virtual machine hosted by Mac OS with cmake 3.8.1 but kept getting the following error message:

```
Errors << glog_catkin:make /media/psf/catkin_ws/logs/glog_catkin/build.make.003.log                                                                                                                
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: /media/psf/catkin_ws/build/glog_catkin/glog_src-prefix/src/v0.3.4.zip
CMake Error at glog_src-stamp/extract-glog_src.cmake:33 (message):
  error: extract of
  '/media/psf/catkin_ws/build/glog_catkin/glog_src-prefix/src/v0.3.4.zip'
  failed

make[2]: *** [glog_src-prefix/src/glog_src-stamp/glog_src-download] Error 1
make[1]: *** [CMakeFiles/glog_src.dir/all] Error 2
make: *** [all] Error 2
cd /media/psf/catkin_ws/build/glog_catkin; catkin build --get-env glog_catkin | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```

**Comment by hitimo** [comment]
@XiaoGene What was the outcome?

**Comment by XiaoGene** [comment]
The error was because I used the shared folders in the virtual machine. Since the shared folder catkin_ws is mounted to `/media/catkin_ws` in my Ubuntu, extracting zip files to this directory may have permission issues. The error was then fixed by not using shared folders and putting catkin_ws folder into user directory.

**Comment by hitimo** [comment]
Okay that makes sense. Thanks for the update; maybe helpful to others.
